Algoritmo "MultiplosDe2"
// Disciplina : Logica de Programacao
// Professor  : Marcos Monteiro
// Descricao  : Apresenta os multiplos de 2 entre 0 e 100
// Autor      : Paulo Vitor dos Santos
// Data atual : 27/10/2022

Var
   // Variavel i(contador)
   i: inteiro

Inicio
   // Apresenta os multiplos de 2 entre 0 e 100
   escreval("Multiplos de 2 entre 0 e 100:")
   para i de 0 ate 100 passo i + 2 faca
      escreval(i)
   fimpara
Fimalgoritmo